/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

export interface AccountKeyResponseDto {
	/** UUID único da chave PIX */
	id: string;
	/** Chave PIX (email, telefone, CPF, CNPJ ou chave aleatória) */
	key: string;
	/** UUID da conta à qual a chave está vinculada */
	accountId: string;
	/** Data de criação da chave PIX */
	createdAt: string;
}
