/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

export interface AccountResponseDto {
	/** UUID único da conta */
	id: string;
	/** UUID do usuário proprietário da conta */
	userId: string;
	/** Número da conta bancária */
	accountNumber: string;
	/**
	 * Saldo da conta em centavos
	 * @minimum 0
	 */
	balance: number;
	/** Data de criação da conta */
	createdAt: string;
	/** Data da última atualização da conta */
	updatedAt: string;
}
