/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

export interface AccountKeyDto {
	/** UUID único da chave */
	id: string;
	/** Chave PIX */
	key: string;
	/** Data de criação da chave */
	createdAt: string;
}
