/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */
import type { AccountInfoDtoAccountKeysItem } from "./accountInfoDtoAccountKeysItem";

export interface AccountInfoDto {
	/** Número da conta bancária */
	accountNumber: string;
	/**
	 * Saldo da conta em centavos
	 * @minimum 0
	 */
	balance: number;
	/** Chaves PIX vinculadas à conta */
	accountKeys?: AccountInfoDtoAccountKeysItem[];
}
