/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status inicial da transação (sempre PENDING na criação)
 */
export type CreateTransactionResponseDtoStatus =
	(typeof CreateTransactionResponseDtoStatus)[keyof typeof CreateTransactionResponseDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateTransactionResponseDtoStatus = {
	PENDING: "PENDING",
	PROCESSING: "PROCESSING",
	COMPLETED: "COMPLETED",
	FAILED: "FAILED",
	CANCELLED: "CANCELLED",
} as const;
