/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTransactionResponseDtoStatus } from "./createTransactionResponseDtoStatus";

export interface CreateTransactionResponseDto {
	/** UUID único da transação criada */
	transactionId: string;
	/** Status inicial da transação (sempre PENDING na criação) */
	status: CreateTransactionResponseDtoStatus;
}
