/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAccountKeyDto {
	/** UUID da conta à qual a chave PIX será vinculada */
	accountId: string;
	/** Chave PIX (email, telefone, CPF, CNPJ ou chave aleatória) */
	key: string;
}
