/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */
import type { FindAllByAccountType } from "./findAllByAccountType";

export type FindAllByAccountParams = {
	/**
	 * Número máximo de transações a serem retornadas
	 */
	limit?: unknown;
	/**
	 * Número da página a ser retornada
	 */
	page?: unknown;
	/**
	 * Filtrar por tipo de transação: 'sent' (enviadas) ou 'received' (recebidas)
	 */
	type?: FindAllByAccountType;
};
