/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

export type FindAllByAccountType =
	(typeof FindAllByAccountType)[keyof typeof FindAllByAccountType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindAllByAccountType = {
	sent: "sent",
	received: "received",
} as const;
