/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

export type FindAllParams = {
	/**
	 * Número da página (começa em 1)
	 * @minimum 1
	 */
	page?: number;
	/**
	 * Quantidade de usuários por página
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
};
