/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionResponseDtoStatus } from "./transactionResponseDtoStatus";

export interface TransactionResponseDto {
	/** UUID único da transação */
	id: string;
	/**
	 * Valor da transação em centavos
	 * @minimum 1
	 */
	amount: number;
	/** UUID da conta remetente */
	senderId: string;
	/** UUID da conta destinatária */
	receiverId: string;
	/** Status da transação */
	status: TransactionResponseDtoStatus;
	/** Data de criação da transação */
	createdAt: string;
}
