/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTransactionDto {
	/**
	 * Valor da transação em centavos
	 * @minimum 1
	 */
	amount: number;
	/** UUID da conta remetente (de onde o dinheiro será debitado) */
	senderId: string;
	/** UUID da conta destinatária (para onde o dinheiro será creditado) */
	receiverId: string;
	/** UUID único da transação a ser atualizada */
	transactionId: string;
}
