/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Bank API
 * API RESTful completa para gerenciamento bancário com suporte a autenticação JWT, operações de contas, transações e gerenciamento de usuários.
 * OpenAPI spec version: 1.0.0
 */

export interface UserResponseDto {
	/** UUID único do usuário */
	id: string;
	/** Nome completo do usuário */
	name: string;
	/** Email do usuário */
	email: string;
	/** Data de criação do usuário */
	createdAt: string;
	/** Data da última atualização do usuário */
	updatedAt: string;
}
