name: my-better-t-app

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_bank
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # RabbitMQ Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist RabbitMQ data
      - rabbitmq_log:/var/log/rabbitmq # Persist RabbitMQ logs
  postgres:
    image: postgres:18
    container_name: bank
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - bank_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  bank_postgres_data:
  rabbitmq_data:
  rabbitmq_log:
